### ISSUE TITLE
Is there something like the status2d patch to add colors?

### ISSUE THREAD

**Issue by root2185** [kyrie-z/slstatus#1]
Using https://dwm.suckless.org/patches/status2d/ you can add colors and squares:
![2022-10-21_19-49-32](https://user-images.githubusercontent.com/32654091/197258118-7dd3880a-5d50-4b54-a809-764b41332556.png)
From https://www.reddit.com/r/unixporn/comments/y660xv/dwm_cute_halloween_how_did_i_do/.

Is there something like that for slstatus?

**Comment by drkhsh** [comment]
@Scorpion2185 This repo is an unofficial fork of suckless' GitHub mirror, which is operated by myself (I'm the maintainer). The place to ask such questions is the suckless mailing list.

**Comment by root2185** [comment]
stastus2d works here too.
e.g. `{ kernel_release,	"^c#FFFFFF^ ^b#000000^  %s" ,	NULL},`
